const Types = {
  ADD_USER: "ADD_USER",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  UPDATE_USERS: "UPDATE_USERS",
  UPDATE_USERS_SUCCESS: "UPDATE_USERS_SUCCESS",
  CONNECT_TO_SOCKET: "CONNECT_TO_SOCKET",
  CONNECT_TO_SOCKET_SUCCESS: "CONNECT_TO_SOCKET_SUCCESS",
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_MESSAGE_SUCCESS: "ADD_MESSAGE_SUCCESS",
  UPDATE_MESSAGES: "UPDATE_MESSAGES",
  UPDATE_MESSAGES_SUCCESS: "UPDATE_MESSAGES_SUCCESS",
};

export default Types;
